ORCA_EXEC_COMMAND = "/opt/orca5/orca"
GAUSSIAN_EXEC_COMMAND = "srung"
DEFAULT_NUM_OF_PROCS = 24
DEFAULT_METHOD = "RHF/STO-3G"
DEFAULT_ORCA_METHOD = "r2SCAN-3c TightSCF"
DEFAULT_ORCA_METHOD = "M06-2X 6-31+G(d) CPCM(water)"
DEFAULT_CHARGE = 0
DEFAULT_MULTIPL = 1
